interface Resources {
  SEO: {
    tags: 'Os tópicos do meu blog'
    author: 'Sobre mim'
    about: 'Sobre'
  }
  about: {
    about: 'Sobre'
  }
  blog: {
    tags: 'Categorias'
  }
  common: {
    home: 'Início'
    blog: 'Blog'
    tags: 'Categorias'
    tagstitle: 'Categorias'
    projects: 'Projetos'
    about: 'Sobre'
    lang: 'Idioma'
    showmenu: 'Mostrar menu'
    scrollcomment: 'Rolar para comentar'
    scrolltop: 'Voltar ao topo'
    darkmode: 'Alternar para o modo escuro'
    content: 'Conteúdo'
    kbarplaceholder: 'Digite um comando ou pesquise'
    loading: 'Carregando...'
    noresults: 'Nenhum resultado encontrado...'
    poststagged: 'Ver posts marcados'
    series: 'Série:'
    episodes: 'Episódio:'
    share: 'COMPARTILHAR'
    facebookshare: 'botão de compartilhamento do facebook'
    twittershare: 'botão de compartilhamento do twitter'
    linkedinshare: 'botão de compartilhamento do linkedin'
    redditshare: 'botão de compartilhamento do reddit'
    whatsappshare: 'botão de compartilhamento do whatsapp'
    telegramshare: 'botão de compartilhamento do telegram'
    pinterestshare: 'botão de compartilhamento do pinterest'
    threadsshare: 'botão de compartilhamento do threads'
    theme: 'Tema'
    light: 'Claro'
    dark: 'Escuro'
    system: 'Sistema'
    name: 'Nome*'
    title: 'Me contate'
    mail: 'Email*'
    button: 'Enviar'
    error: 'Ops, algo deu errado!'
    thanks: 'Obrigado por entrar em contato, responderei em breve!'
    message: 'Mensagem*'
    copyurl: 'Copiar URL'
    urlcopied: 'URL copiada!'
    contact: 'Contato'
    back: 'Voltar'
    settings: 'Configurações'
    language: 'Idioma'
    french: 'Francês'
    english: 'Inglês'
    sidetoc: 'Nesta página:'
  }
  footer: {}
  home: {
    greeting: 'Os mais recentes'
    description: 'Um blog criado com Next.js, i18n e Tailwind.css'
    more: 'Leia mais'
    all: 'Todos os artigos'
    moreaboutme: 'Mais sobre mim'
    featured: 'Em destaque'
    morefeatured: 'Mais artigos em destaque'
    morerecent: 'Mais artigos recentes'
    search: 'Busca'
    searchposts: 'Buscar artigos'
    comment: 'Carregar comentários'
    pub: 'Publicado em'
    authors: 'Autores'
    name: 'Nome'
    nexta: 'Próximo Artigo'
    preva: 'Artigo Anterior'
    nextp: 'Próximo'
    prevp: 'Anterior'
    of: 'de'
    back: 'Voltar ao blog'
    twitter: 'Discutir no Twitter'
    github: 'Ver no GitHub'
    draft: 'Em Rascunho'
    noposts: 'Nenhum artigo encontrado'
    poststagged: 'Ver posts marcados'
  }
  newsletter: {
    mail: 'Endereço de E-mail'
    title: 'Inscreva-se na newsletter'
    messageError: 'Seu endereço de e-mail é inválido ou já está inscrito!'
    placeholderSuccess: 'Você está inscrito! 🎉'
    placeholderDefault: 'Digite seu endereço de e-mail'
    buttonSuccess: 'Obrigado!'
    buttonDefault: 'Inscrever-se'
  }
  notfound: {
    title: 'Desculpe, não conseguimos encontrar esta página.'
    description: 'Não se preocupe, você poderá encontrar muitas outras coisas na nossa página inicial.'
    back: 'Voltar para a página inicial'
  }
  projects: {
    title: 'Projetos'
    description: 'Apresente seus projetos com uma imagem (16 x 9)'
    read: 'Leia mais'
    visit: 'Visitar o projeto'
    subtitle: 'Aqui você encontrará informações sobre meus projetos atuais.'
    linkto: 'Link para'
  }
}

export default Resources
